export const TRANSLATED_RESULTS = {
  VERY_UNLIKELY: 'MUY IMPROBABLE',
  UNLIKELY: 'IMPROBABLE',
  VERY_LIKELY: 'MUY PROBABLE',
  LIKELY: 'PROBABLE',
  UNKNOWN: 'DESCONOCIDO',
  POSSIBLE: 'POSIBLE',
};
